import { StyleSheet } from "react-native";
export const color = {
  sky: "#E8F3F7",
  paper: "#FFFCF3",
  ink: "#203C4B",
  blue: "#2463A6",
  yellow: "#FFD166",
  mint: "#89D5BD",
  line: "#B4CCD4",
  muted: "#516C79",
  red: "#9A3444",
  white: "#FFFFFF",
  blueDark: "#194B80",
  blueLight: "#E4F0FB",
  mintDark: "#287860",
  mintLight: "#D9EFE7",
  yellowDark: "#B18428",
  metal: "#DCE8EC",
  wood: "#D7AD79",
  woodDark: "#A17849",
};
export const ui = StyleSheet.create({
  page: { flex: 1, backgroundColor: color.sky },
  content: {
    padding: 24,
    gap: 24,
    width: "100%",
    maxWidth: 1080,
    alignSelf: "center",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
  },
  title: {
    fontSize: 36,
    fontWeight: "800",
    color: color.ink,
    letterSpacing: -0.8,
  },
  body: { fontSize: 19, lineHeight: 28, color: color.ink },
  small: { fontSize: 15, lineHeight: 22, color: color.muted },
  panel: {
    backgroundColor: color.paper,
    borderRadius: 28,
    padding: 26,
    gap: 20,
    borderWidth: 2,
    borderColor: color.line,
  },
  button: {
    minHeight: 60,
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 20,
    backgroundColor: color.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { fontSize: 20, fontWeight: "700", color: "white" },
  pressed: { transform: [{ translateY: 2 }], opacity: 0.88 },
  secondary: {
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: color.line,
  },
  secondaryText: { color: color.ink },
  error: { color: color.red, fontSize: 17, lineHeight: 25 },
  input: {
    minHeight: 60,
    borderWidth: 2,
    borderColor: color.line,
    borderRadius: 16,
    padding: 14,
    fontSize: 24,
    color: color.ink,
    backgroundColor: "white",
  },
});
