import { StyleSheet } from "react-native";
export const color = {
  sky: "#DCECFA",
  paper: "#FFFDF5",
  ink: "#203B57",
  blue: "#205AB5",
  yellow: "#FFD361",
  mint: "#76CEB3",
  line: "#AEC9DE",
  muted: "#526C83",
  red: "#9A3444",
};
export const ui = StyleSheet.create({
  page: { flex: 1, backgroundColor: color.sky },
  content: {
    padding: 24,
    gap: 22,
    width: "100%",
    maxWidth: 1080,
    alignSelf: "center",
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flexWrap: "wrap",
  },
  title: {
    fontSize: 36,
    fontWeight: "800",
    color: color.ink,
    letterSpacing: -1,
  },
  body: { fontSize: 19, lineHeight: 28, color: color.ink },
  small: { fontSize: 15, lineHeight: 22, color: color.muted },
  panel: {
    backgroundColor: color.paper,
    borderRadius: 28,
    padding: 26,
    gap: 20,
  },
  button: {
    minHeight: 60,
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 20,
    backgroundColor: color.blue,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonText: { fontSize: 20, fontWeight: "700", color: "white" },
  secondary: {
    backgroundColor: "white",
    borderWidth: 2,
    borderColor: color.line,
  },
  secondaryText: { color: color.ink },
  error: { color: color.red, fontSize: 17, lineHeight: 25 },
  input: {
    minHeight: 60,
    borderWidth: 2,
    borderColor: color.line,
    borderRadius: 16,
    padding: 14,
    fontSize: 24,
    color: color.ink,
    backgroundColor: "white",
  },
});
